/**
 * Created by randomnum on 2015/6/14.
 */
require.config({
    paths: {
        'domReady': '../scripts/util/domReady',
        'jquery': '../scripts/util/jquery',
        "mustache": "../scripts/util/mustache",
        "codemirror": "../scripts/util/codemirror-compressed",
        "codemirror/stex": "../scripts/util/CodeMirror/stex",
        "jquery.ui": "../scripts/util/jquery-ui.min",
        "jquery.form": "../scripts/util/jquery.form",
        "jquery.markitup": "../scripts/util/markitup/jquery.markitup",
        "jquery.leanModal": "../scripts/util/jquery.leanModal.min",
        "jquery.ajaxQueue": "../scripts/util/jquery.ajaxQueue",
        "jquery.smoothScroll": "../scripts/util/jquery.smooth-scroll.min",
        "jquery.timepicker": "../scripts/util/timepicker/jquery.timepicker",
        "jquery.cookie": "../scripts/util/jquery.cookie",
        "jquery.qtip": "../scripts/util/jquery.qtip.min",
        "jquery.scrollTo": "../scripts/util/jquery.scrollTo-1.4.2-min",
        "jquery.flot": "../scripts/util/flot/jquery.flot.min",
        "jquery.fileupload": "../scripts/util/jQuery-File-Upload/js/jquery.fileupload",
        "jquery.fileupload-process": "../scripts/util/jQuery-File-Upload/js/jquery.fileupload-process",
        "jquery.fileupload-validate": "../scripts/util/jQuery-File-Upload/js/jquery.fileupload-validate",
        "jquery.iframe-transport": "../scripts/util/jQuery-File-Upload/js/jquery.iframe-transport",
        "jquery.inputnumber": "../scripts/util/html5-input-polyfills/number-polyfill",
        "jquery.immediateDescendents": "coffee/src/jquery.immediateDescendents",
        "datepair": "../scripts/util/timepicker/datepair",
        "date": "../scripts/util/date",
        "underscore": "../scripts/util/underscore-min",
        "underscore.string": "../scripts/util/underscore.string.min",
        "backbone": "../scripts/util/backbone-min",
        "backbone.associations": "../scripts/util/backbone-associations-min",
        "backbone.paginator": "../scripts/util/backbone.paginator.min",
        "tinymce": "../scripts/util/tinymce/js/tinymce/tinymce.full.min",
        "jquery.tinymce": "../scripts/util/tinymce/js/tinymce/jquery.tinymce.min",
        "xmodule": "/xmodule/xmodule",
        "xblock/core": "js/xblock/core",
        "xblock": "coffee/src/xblock",
        "utility": "js/src/utility",
        "accessibility": "js/src/accessibility_tools",
        "draggabilly": "../scripts/util/draggabilly.pkgd",
        "URI": "../scripts/util/URI.min",
        "ieshim": "js/src/ie_shim",
        "tooltip_manager": "js/src/tooltip_manager",
        // Files needed for Annotations feature
        "annotator": "../scripts/util/ova/annotator-full",
        "annotator-harvardx": "../scripts/util/ova/annotator-full-firebase-auth",
        "video.dev": "../scripts/util/ova/video.dev",
        "vjs.youtube": '../scripts/util/ova/vjs.youtube',
        "rangeslider": '../scripts/util/ova/rangeslider',
        "share-annotator": '../scripts/util/ova/share-annotator',
        "richText-annotator": '../scripts/util/ova/richText-annotator',
        "reply-annotator": '../scripts/util/ova/reply-annotator',
        "grouping-annotator": '../scripts/util/ova/grouping-annotator',
        "tags-annotator": '../scripts/util/ova/tags-annotator',
        "diacritic-annotator": '../scripts/util/ova/diacritic-annotator',
        "flagging-annotator": '../scripts/util/ova/flagging-annotator',
        "jquery-Watch": '../scripts/util/ova/jquery-Watch',
        "openseadragon": '../scripts/util/ova/openseadragon',
        "osda": '../scripts/util/ova/OpenSeaDragonAnnotation',
        "ova": '../scripts/util/ova/ova',
        "catch": '../scripts/util/ova/catch/js/catch',
        "handlebars": '../scripts/util/ova/catch/js/handlebars-1.1.2'
    }
});

